import { Router } from 'express';
import authRoutes from './auth.routes.js';
import categoriesRoutes from './categories.routes.js';
import transactionsRoutes from './transactions.routes.js';
import usersRoutes from './users.routes.js';
import googleCalendarRoutes from './googleCalendar.routes.js';
import meiGuideRoutes from './mei-guide.routes.js';
import meiNotasRoutes from './mei-notas.routes.js';
import recorrenciasRoutes from './recorrencias.routes.js';
import adminRoutes from './admin.routes.js';
import healthRoutes from './health.routes.js';
import empresaInvitesRoutes from './empresa-invites.routes.js';
import cronRoutes from './cron.routes.js';
import openclawRoutes from './openclaw.routes.js';
import zapiRoutes from './zapi.routes.js';
import internalAccessRequestsRoutes from './internal-access-requests.routes.js';
import moedasGlobaisRoutes from './moedas-globais.routes.js';
import billingRoutes from './billing.routes.js';
const router = Router();

router.use('/auth', authRoutes);
router.use('/categories', categoriesRoutes);
router.use('/transactions', transactionsRoutes);
router.use('/users', usersRoutes);
router.use('/invites', empresaInvitesRoutes);
router.use('/admin', adminRoutes);
router.use('/billing', billingRoutes);
router.use('/health', healthRoutes);
router.use('/google-calendar', googleCalendarRoutes);
router.use('/mei-guide', meiGuideRoutes);
router.use('/mei-notas', meiNotasRoutes);
router.use('/notas', meiNotasRoutes);
router.use('/recorrencias', recorrenciasRoutes);
router.use('/cron', cronRoutes);
router.use('/bot', openclawRoutes);
router.use('/webhooks/zapi', zapiRoutes);
router.use('/internal/access-requests', internalAccessRequestsRoutes);
router.use('/moedas-globais', moedasGlobaisRoutes);
export default router;
